[package]
name = "service-discovery"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "service-discovery"
path = "src/main.rs"

[dependencies]
router-api = { path = "../../lib/router-api" }
router-core = { path = "../../lib/router-core" }
router-galactic = { path = "../../lib/router-galactic" }
kube = { workspace = true }
kube-runtime.workspace = true
k8s-openapi.workspace = true
tokio.workspace = true
serde = { workspace = true }
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
